### ISSUE TITLE
Header Link to Document Source

### ISSUE THREAD

**Issue by flywire** [portfolio-performance/portfolio-help#23]
Can the MkDocs Header Page link be enabled for direct navigation to page source: https://www.mkdocs.org/user-guide/configuration/#edit_uri ? (Click  _Edit on GitHub_.)

**Comment by hug-sch** [comment]
Hi,
The edit-uri option is set to:

```
repo_url: https://github.com/portfolio-performance/portfolio-help
edit_uri: blob/master/docs/
```


According to the link, this will result in:
On GitHub and GitLab, the default "edit" path (edit/master/docs/) opens the page in the online editor. This functionality requires that the user have and be logged in to a GitHub/GitLab account. Otherwise, the user will be redirected to a login/signup page. Alternatively, use the "blob" path (blob/master/docs/) to open a read-only view, which supports anonymous access.

How would you like it to be changed?

**Comment by flywire** [comment]
> How would you like it to be changed?

Fix it but I don't know how. (I raised the issue not the solution. :wink: )

The functionality is good when it works. I had a look around but I couldn't see an easy answer so it needs more research. It seems to work on MkDocs but not with the Material theme. It could be a template issue or something to do with language version (as I understand it there is not translation, just different versions for different languages).

**Comment by hug-sch** [comment]
But, what exactly isn't working for you?

**Comment by flywire** [comment]
![image](https://github.com/portfolio-performance/portfolio-help/assets/11288701/6d3dfe35-ebf6-41cb-99b6-a89e29d71a16)

**Comment by flywire** [comment]
https://squidfunk.github.io/mkdocs-material/upgrade/#contentaction

> ...must now be explicitly enabled.

```
theme:
  features:
    - content.action.edit
```

**Comment by hug-sch** [comment]
Thanks! Should be working now.

**Comment by flywire** [comment]
close with 3f207c4
